name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
      
  deploy:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd openpecha-services
            cd openpecha-editor
            git pull origin main
            cd ..
            docker-compose up -d --build editor
