name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
      
#   build:
# #     needs: test
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set Environment Variables
#       run: |
#         echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
#     - 
#       name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
#     - 
#       name: Cache Docker layers
#       uses: actions/cache@v2
#       with:
#         path: /tmp/.buildx-cache
#         key: ${{ runner.os }}-buildx-${{ github.sha }}
#         restore-keys: |
#           ${{ runner.os }}-buildx-
#     - 
#       name: Login to DockerHub
#       uses: docker/login-action@v1 
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
#     - 
#       name: Build and push Docker image
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         push: true
#         tags: openpecha/openpecha-editor:prod-${{ env.GIT_SHA }}
#         cache-from: type=local,src=/tmp/.buildx-cache
#         cache-to: type=local,dest=/tmp/.buildx-cache-new
#         build-args: |
#           OPENPECHA_API_URL=https://openpecha.org
#           APP_DOMAIN_DEV=localhost
#           APP_DOMAIN_STAG=stag.openpecha.org
#           APP_DOMAIN_PROD=openpecha.org
#           APP_NAME=openpecha
#           APP_ENV=production
#           GITHUB_OAUTH_CLIENT_ID=70014100b75704b5f39d
#           GITHUB_OAUTH_URL=https://github.com/login/oauth/authorize
#           AUTH0_DOMAIN=bdrc-io.auth0.com
#           AUTH0_CLIENT_ID=UY2zbsST2S31w6sM5TSHaOBRZPVErccc
#           AUTH0_AUDIENCE=https://bdrc-io.auth0.com/api/v2/
#           AUTH0_RESPONSETYPE=token id_token
#           AUTH0_SCOPE=openid
#           IFFFServerURL=https://iiif.bdrc.io
#     -
#       # Temp fix
#       # https://github.com/docker/build-push-action/issues/252
#       # https://github.com/moby/buildkit/issues/1896
#       name: Move cache
#       run: |
#         rm -rf /tmp/.buildx-cache
#         mv /tmp/.buildx-cache-new /tmp/.buildx-cache
#     -
#       name: Image digest
#       run: echo ${{ steps.docker_build.outputs.digest }}
        
  deploy:
#     needs: build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set Environment Variables
        run: |
          echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      - 
        uses: appleboy/ssh-action@master
        env:
          SHA: ${{ env.GIT_SHA }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          envs: SHA
          script_stop: true
#           script: docker service update --image "openpecha/openpecha-editor:prod-$SHA" openpecha-org_editor
          script: |
            echo "docker service update --image openpecha/openpecha-editor:prod-${SHA} openpecha-org_editor"
            echo ${{ env.GIT_SHA }}
